// Problem 29: Distinct Powers
// How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
// Answer: 9183

package main

import (
	"fmt"
	"math/big"
	"sort"
	"time"
)

func solve() int {
	terms := make([]string, 0, 9801)

	for a := int64(2); a <= 100; a++ {
		for b := int64(2); b <= 100; b++ {
			val := new(big.Int).Exp(big.NewInt(a), big.NewInt(b), nil)
			terms = append(terms, val.String())
		}
	}

	sort.Strings(terms)

	distinct := 1
	for i := 1; i < len(terms); i++ {
		if terms[i] != terms[i-1] {
			distinct++
		}
	}

	return distinct
}

func benchmark(iterations int) time.Duration {
	// Warmup
	for i := 0; i < 10; i++ {
		solve()
	}

	start := time.Now()
	var result int
	for i := 0; i < iterations; i++ {
		result = solve()
	}
	elapsed := time.Since(start)
	fmt.Printf("Result: %d (%.2f ns/op)\n", result, float64(elapsed.Nanoseconds())/float64(iterations))
	return elapsed
}

func main() {
	const iterations = 100

	fmt.Println("Problem 29: Distinct Powers")
	fmt.Println("============================")
	fmt.Printf("Counting distinct terms in a^b, Iterations: %d\n\n", iterations)

	benchmark(iterations)
}
