// Answer: 9183
// Problem 29: Distinct Powers
// How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

package main

import (
	"math/big"
	"sort"

	"github.com/august-hill/ProjectEuler.Go/bench"
)

func solve() int64 {
	terms := make([]string, 0, 9801)

	for a := int64(2); a <= 100; a++ {
		for b := int64(2); b <= 100; b++ {
			val := new(big.Int).Exp(big.NewInt(a), big.NewInt(b), nil)
			terms = append(terms, val.String())
		}
	}

	sort.Strings(terms)

	distinct := 1
	for i := 1; i < len(terms); i++ {
		if terms[i] != terms[i-1] {
			distinct++
		}
	}

	return int64(distinct)
}

func main() { bench.Run(29, solve) }
